# Generated by Django 4.2.1 on 2023-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='userid',
            field=models.CharField(default=models.TextField(max_length=20), max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='userpw',
            field=models.TextField(default=models.TextField(max_length=20)),
        ),
    ]
