# Generated by Django 4.2.4 on 2023-08-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_userdetail_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='user',
            new_name='detail',
        ),
    ]
