# Generated by Django 4.2.4 on 2023-08-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_user_userdetail_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='detail',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userid',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userpw',
            field=models.TextField(),
        ),
    ]
