# Generated by Django 4.2.4 on 2023-08-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_detail_userdetail_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='userpw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='userid',
            new_name='username',
        ),
    ]
