# Generated by Django 4.2.4 on 2023-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltTextInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
