# Generated by Django 4.2.3 on 2023-07-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='create',
            name='example_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
