# Generated by Django 4.2.3 on 2023-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_alter_create_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='create',
            name='picture_zip',
            field=models.FileField(blank=True, null=True, upload_to='picture_zips/'),
        ),
        migrations.RemoveField(
            model_name='create',
            name='picture',
        ),
        migrations.AddField(
            model_name='create',
            name='picture',
            field=models.ManyToManyField(blank=True, to='posting.image'),
        ),
    ]
