# Generated by Django 4.2.3 on 2023-07-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_remove_create_picture_create_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create',
            new_name='Posting',
        ),
    ]
