# Generated by Django 4.2.3 on 2023-07-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0012_remove_image_images_image_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='posted_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posting.posting'),
        ),
    ]
