# Generated by Django 4.2.1 on 2023-08-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0016_image_description_posting_remaining_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='saved_description',
            field=models.BooleanField(default=False),
        ),
    ]
