# Generated by Django 4.2.3 on 2023-07-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('example_picture', models.ImageField(blank=True, null=True, upload_to='example_pictures/')),
                ('example_description', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.FileField(upload_to='pictures/')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
