# Generated by Django 4.2.3 on 2023-07-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_image_create_picture_zip_remove_create_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create',
            name='picture',
        ),
        migrations.AddField(
            model_name='create',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posting.image'),
        ),
    ]
