# Generated by Django 4.2.3 on 2023-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_remove_create_picture_create_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to=''),
        ),
    ]
