# Generated by Django 4.2.3 on 2023-07-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_alter_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.BinaryField(),
        ),
    ]
