# Generated by Django 4.2.3 on 2023-07-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_rename_create_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='data',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='quantity',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posted_images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posting.posting'),
        ),
    ]
