# Generated by Django 4.2.3 on 2023-07-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_posting_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='posting',
        ),
        migrations.AddField(
            model_name='image',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.posting'),
        ),
    ]
