# Generated by Django 4.2.3 on 2023-07-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0013_alter_image_image_alter_image_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posted_images/'),
        ),
    ]
